/*
 * Copyright 2010-2015 Allette Systems (Australia)
 * http://www.allette.com.au
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.pageseeder.diffx.test;

import static org.junit.jupiter.api.Assertions.*;

import org.opentest4j.AssertionFailedError;
import org.pageseeder.diffx.action.Action;
import org.pageseeder.diffx.action.Actions;
import org.pageseeder.diffx.action.Operator;
import org.pageseeder.diffx.event.DiffXEvent;
import org.pageseeder.diffx.event.OpenElementEvent;
import org.pageseeder.diffx.event.impl.CloseElementEventImpl;
import org.pageseeder.diffx.event.impl.OpenElementEventImpl;
import org.pageseeder.diffx.sequence.EventSequence;
import org.pageseeder.diffx.sequence.PrefixMapping;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParserFactory;
import java.io.IOException;
import java.io.StringReader;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * A utility class providing a collection of assertions for testing diff.
 */
public final class DiffAssertions {

  /**
   * Asserts that the applying list of actions generates a list of events that match the events
   */
  public static void assertActionsMatchEvents(List<? extends DiffXEvent> events, List<Action> actions,boolean positive) {
    String exp = TestHandler.format(events);
    String got = TestHandler.format(Actions.generate(actions, positive));
    assertEquals(exp, got, "Events generated by applying actions do not match the supplied events");
  }

  /**
   * Asserts that the list of actions is applicable to the specified sequences.
   */
  public static void assertIsApplicable(List<? extends DiffXEvent> seq1, List<? extends DiffXEvent> seq2, List<Action> actions) {
    assertTrue(Actions.isApplicable(seq1, seq2, actions), "The resulting diff is not applicable");
  }

  /**
   * Asserts that the list of actions lead to the correct XML
   */
  public static void assertIsCorrect(List<? extends DiffXEvent> seq1, List<? extends DiffXEvent> seq2, List<Action> actions) {
    // Apply to second sequence to ensure we get the first
    String got1 = Events.toXML(Actions.generate(actions, true));
    String exp1 = Events.toXML(seq1);
    assertEquals(exp1, got1, "Applying diff to #2 did not produce #1");

    // Apply to first sequence to ensure we get the second
    String got2 = Events.toXML(Actions.generate(actions, false));
    String exp2 = Events.toXML(seq2);
    assertEquals(exp2, got2, "Applying diff to #1 did not produce #2");
  }

  /**
   * Asserts that the list of actions lead to the correct XML
   */
  public static void assertIsCorrect(EventSequence a, EventSequence b, List<Action> actions) {
    // Apply to second sequence to ensure we get the first
    String got1 = Events.toXML(Actions.generate(actions, true), a.getPrefixMapping());
    String exp1 = Events.toXML(a.events(), a.getPrefixMapping());
    assertEquals(exp1, got1, "Applying diff to #2 did not produce #1");

    // Apply to first sequence to ensure we get the second
    String got2 = Events.toXML(Actions.generate(actions, false), b.getPrefixMapping());
    String exp2 = Events.toXML(b.events(), b.getPrefixMapping());
    assertEquals(exp2, got2, "Applying diff to #1 did not produce #2");
  }

  public static void assertIsWellFormedXML(List<Action> actions) {
    List<Action> wrapped = new ArrayList<>();
    // We wrap the actions in case we have a completely different output
    OpenElementEvent root = new OpenElementEventImpl("root");
    wrapped.add(new Action(Operator.MATCH, Collections.singletonList(root)));
    wrapped.addAll(actions);
    wrapped.add(new Action(Operator.MATCH, Collections.singletonList(new CloseElementEventImpl(root))));
    DiffAssertions.assertIsWellFormedXML(TestActions.toXML(wrapped));
  }

  public static void assertIsWellFormedXML(List<Action> actions, PrefixMapping mapping) {
    List<Action> wrapped = new ArrayList<>();
    // We wrap the actions in case we have a completely different output
    OpenElementEvent root = new OpenElementEventImpl("root");
    wrapped.add(new Action(Operator.MATCH, Collections.singletonList(root)));
    wrapped.addAll(actions);
    wrapped.add(new Action(Operator.MATCH, Collections.singletonList(new CloseElementEventImpl(root))));
    DiffAssertions.assertIsWellFormedXML(TestActions.toXML(wrapped, mapping));
  }

  /**
   * Asserts that the specified XML string is well formed.
   *
   * @param xml THe XML string to test
   */
  public static void assertIsWellFormedXML(String xml)  {
    try {
      InputSource source = new InputSource(new StringReader(xml));
      SAXParserFactory factory = SAXParserFactory.newInstance();
      factory.newSAXParser().parse(source, new DefaultHandler());
    } catch (SAXException ex) {
      throw new AssertionError("XML is not well-formed");
    } catch (ParserConfigurationException ex) {
      throw new IllegalStateException("Unable to check assertions due to", ex);
    } catch (IOException ex) {
      throw new UncheckedIOException("Unable to check assertions due to", ex);
    }
  }

  public static void assertMatchTestOutput(List<Action> actions, String[] exp) {
    // check the possible values
    String output = toTestOutput(actions, PrefixMapping.noNamespace());
    for (String s : exp) {
      if (s.equals(output)) return;
    }
    assertEquals(exp[0], output);
  }

  public static void assertMatchTestOutput(List<Action> actions, String[] exp, PrefixMapping mapping) {
    // check the possible values
    String output = toTestOutput(actions, mapping);
    for (String s : exp) {
      if (s.equals(output)) return;
    }
    assertEquals(exp[0], output);
  }

  /**
   * Handle the specified actions with the handler.
   *
   * @param actions Action to handle
   * @return output of the test handler
   */
  public static String toTestOutput(List<Action> actions, PrefixMapping mapping) {
    TestHandler handler = new TestHandler(mapping);
    Actions.handle(actions, handler);
    return handler.getOutput();
  }


  public static void assertEqualsAny(String[] expected, String actual) {
    // check the possible values
    for (String exp : expected) {
      if (exp.equals(actual)) return;
    }
    throw new AssertionFailedError("Actual value did not match any of the expected values", expected, actual);
  }
}
