/*
 * Copyright 2010-2015 Allette Systems (Australia)
 * http://www.allette.com.au
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.pageseeder.diffx.test;

import java.io.File;

/**
 * A testing utility class.
 *
 * @author Christophe Lauret (Weborganic)
 * @version 0.9.0
 */
public class TestUtils {

  /**
   * Utility class.
   */
  private TestUtils() {
  }

  /**
   * Returns the data directory for the class being tested.
   *
   * <p>The data directory contains test data that is permanent and required for performing tests
   * (eg. source data, etc...)
   *
   * @param c The class being tested.
   * @return the corresponding data directory.
   */
  public static File getDataDirectory(Class<?> c) {
    File data = new File("src/test/resources");
    String dir = c.getName().replaceFirst("org.pageseeder.diffx", "").replace('.', File.separatorChar);
    return new File(data, dir);
  }

  /**
   * Returns the temporary directory for the class being tested.
   *
   * <p>The temporary directory contains test data that is generated by the test from data can be deleted
   * (eg. generated index, etc...)
   *
   * @param c The class being tested.
   * @return the corresponding data directory.
   */
  public static File getTempDirectory(Class<?> c) {
    File data = new File("build/test-tmp");
    String dir = c.getName().replaceFirst("org.pageseeder.diffx", "").replace('.', File.separatorChar);
    return new File(data, dir);
  }

}
